// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxolfglgtpkvrioveuzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14b2xmZ2xndHBrdnJpb3ZldXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTM5ODYsImV4cCI6MjA2OTc4OTk4Nn0.V11-oyEKvNqIso_b3_1q_0SjqBRep808JqEN-hVx-7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});